name: Build Node app using pnpm
description: Build Node app using pnpm

inputs:
  BUILD_DIRECTORY:
    description: 'The directory where the build output will be placed'
    required: true
  ENVIRONMENT:
    description: 'The environment to build for'
    required: true
  NODE_VERSION:
    description: 'The version of Node.js to use'
    required: false
    default: '18.x'
  PNPM_VERSION:
    description: 'The version of pnpm to use'
    required: false
    default: '8.x'
  WORKING_DIRECTORY:
    description: 'The directory where the action should run'
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.NODE_VERSION }}
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.PNPM_VERSION }}
    - name: Install dependencies (pnpm)
      shell: bash
      run: pnpm install --frozen-lockfile
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
    - name: Build application
      shell: bash
      # works with react-scripts >= 4.0.2
      env:
        BUILD_PATH: ${{ inputs.BUILD_DIRECTORY }}
      run: pnpm run build
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
