name: Terraform Version Provisioning Step
description: 'Apply provisioning step'

inputs:
  AWS_ACCESS_KEY_ID_TF:
    description: 'AWS access key'
    required: true
  AWS_SECRET_ACCESS_KEY_TF:
    description: 'AWS secret key'
    required: true
  TF_DIR:
    description: 'Terraform directory'
    required: true
  TF_VERSION:
    description: 'Terraform version'
    required: false
    default: 1.3.x

runs:
  using: composite
  steps:

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID_TF }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY_TF }}
        aws-region: eu-west-3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.TF_VERSION }}

    - name: Terraform init
      shell: bash
      run: |
        terraform -chdir=${{ inputs.TF_DIR }} init \
          -upgrade \
          -reconfigure

    - name: Terraform apply
      shell: bash
      run: |
        terraform -chdir=${{ inputs.TF_DIR }} apply \
          -var current_step=provisioning \
          -auto-approve