name: Check context (ECR, git...)

on:
  workflow_call:
    inputs:
      AWS_DEFAULT_REGION:
        required: true
        type: string
      CLUSTER:
        required: true
        type: string
      SERVICE_NAMESPACE:
        required: true
        type: string
      SERVICES:
        required: true
        type: string
      IMAGE_NAMES:
        required: true
        type: string
      SHA_SHORT:
        description: "Git commit SHA short (without 'sha-' prefix)"
        required: false
        type: string
        default: ''
      NOTIFICATIONS_TEAMS:  # booleans must be treated as string
        required: false
        type: string
        default: 'true'
    secrets:
      AWS_ACCESS_KEY_ID_TF:
        required: true
      AWS_SECRET_ACCESS_KEY_TF:
        required: true
      MS_TEAMS_WEBHOOK_URI:
        required: true
    # Map the workflow outputs to job outputs
    outputs:
      SHA_SHORT:
        description: "Define SHA_SHORT from input or current git commit SHA"
        value: ${{ jobs.check-context.outputs.SHA_SHORT }}
      IMAGE_SHA:
        description: "Define IMAGE_SHA from input or current git commit SHA"
        value: ${{ jobs.check-context.outputs.IMAGE_SHA }}
      IMAGE_EXISTS:
        description: "Indicate if Docker image already exists in ECR for current git commit SHA"
        value: ${{ jobs.check-context.outputs.IMAGE_EXISTS }}
      CLUSTER:
        description: "Cluster name to deploy onto (test, release, prod)"
        value: ${{ jobs.check-context.outputs.CLUSTER }}
      JIRA_CODE:
        description: "JIRA ticket code found in branch name"
        value: ${{ jobs.check-context.outputs.JIRA_CODE }}
      IMAGE_TAG:
        description: "Docker image tag"
        value: ${{ jobs.check-context.outputs.IMAGE_TAG }}
      CREATE_TAG_LATEST:
        description: "Docker image should be tag as latest"
        value: ${{ jobs.check-context.outputs.CREATE_TAG_LATEST }}

jobs:
  check-context:
    name: Check context
    runs-on: ubuntu-latest
    timeout-minutes: 5

    # strategy:
    #   matrix:
    #     image_name: ${{ fromJson(inputs.IMAGE_NAMES) }}

    steps:
      - uses: actions/checkout@v3
        if: ${{ inputs.SHA_SHORT == '' }}

        # Get commit SHA before checking out reusable workflows
      - name: Git output SHA short
        id: git-sha
        if: always()
        run: |
          if [ "${{ inputs.SHA_SHORT }}" != "" ]; then
            SHA_SHORT=${{ inputs.SHA_SHORT }}
          else
            SHA_SHORT=$(git rev-parse --short HEAD)
          fi

          if [ -z ${SHA_SHORT} ]; then
            echo "::error title=Check GIT SHA::GIT SHA can not be empty"
            exit 1
          fi

          echo "::notice title=Check GIT SHA::GIT SHA output value is '${SHA_SHORT}'"
          echo "SHA_SHORT=${SHA_SHORT}" >> ${GITHUB_OUTPUT}
          echo "IMAGE_SHA=sha-${SHA_SHORT}" >> ${GITHUB_OUTPUT}

      # Get commit message before checking out reusable workflows
      - name: Git output commit message
        id: git-commit
        if: always()
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          echo "COMMIT_MESSAGE=${COMMIT_MESSAGE}" >> ${GITHUB_OUTPUT}

      # Checkout reusable workflow to get bash scripts
      - uses: actions/checkout@v3
        with:
          repository: Sonergia/github-reusable-workflows
          ref: '2.x'
          # ref: 'delivery' # Only when testing ############## /!\ ##############

      - name: Install packages (jq)
        run: |
          sudo apt-get -y install jq

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TF }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TF }}
          aws-region: ${{ inputs.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Check if image SHA tag and release tag already exists in ECR, add release tag otherwise
        id: check-image-ecr
        run: ./.github/scripts/check-image-ecr.sh ${{ inputs.SERVICE_NAMESPACE }} "${{ join(fromJson(inputs.IMAGE_NAMES), ' ') }}" ${{ steps.git-sha.outputs.IMAGE_SHA }}

      - name: Set context from git and inputs
        id: set-context
        run: |
          ENVIRONMENT="${{ inputs.CLUSTER }}"
          IS_LAMBDA="false"
          IS_LEGACY="false"
          ./.github/scripts/set-context.sh "${ENVIRONMENT}" "${IS_LAMBDA}" "${IS_LEGACY}"

      - name: Change string case function
        id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ steps.set-context.outputs.CLUSTER }}

      - name: Teams notification content
        id: teams-notification-content
        if: ${{ always() && inputs.NOTIFICATIONS_TEAMS == 'true' }}
        run: |
          if [ ! -z "${{ steps.set-context.outputs.JIRA_CODE }}" ]; then
            CUSTOM_FACT_JIRA_RELEASE_NAME=Jira
            CUSTOM_FACT_JIRA_RELEASE="[${{ steps.set-context.outputs.JIRA_CODE }}](https://sonergia.atlassian.net/browse/${{ steps.set-context.outputs.JIRA_CODE }})"
          else
            CUSTOM_FACT_JIRA_RELEASE_NAME=Release
            CUSTOM_FACT_JIRA_RELEASE="[${{ github.ref_name }}](${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }})"
          fi
          echo "CUSTOM_FACT_JIRA_RELEASE_NAME=${CUSTOM_FACT_JIRA_RELEASE_NAME}" >> ${GITHUB_OUTPUT}
          echo "CUSTOM_FACT_JIRA_RELEASE=${CUSTOM_FACT_JIRA_RELEASE}" >> ${GITHUB_OUTPUT}

      # Notify at the start of workflow
      - name: Notify teams channel
        uses: Sonergia/ms-teams-notification@add-potential-action
        if: ${{ always() && inputs.NOTIFICATIONS_TEAMS == 'true' }}
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: Déploiement service(s) ${{ join(fromJson(inputs.SERVICES), ',') }} -> ${{ steps.set-context.outputs.CLUSTER }} en cours...
          notification-color: 999999
          timezone: Europe/Paris
          # view-commit-changes: true
          # view-workflow-run: true
          # view-pull-request: false
          custom-facts: |
            - name: Status
              value: ⏱ in progress...
            - name: Cluster
              value: ${{ steps.string.outputs.uppercase }}
            - name: Service(s)
              value: ${{ join(fromJson(inputs.SERVICES), ',') }}
            - name: 📖 Commit
              value: "[${{ steps.git-commit.outputs.COMMIT_MESSAGE }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})"
            - name: 📕 Branche
              value: "[${{ github.ref_name }}](${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref }})"
            - name: 🔧 CI/CD
              value: "[Run #${{ github.run_attempt }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
            - name: 📋 ${{ steps.teams-notification-content.outputs.CUSTOM_FACT_JIRA_RELEASE_NAME }}
              value: "${{ steps.teams-notification-content.outputs.CUSTOM_FACT_JIRA_RELEASE }}"
          custom-actions: | # Max 5 actions
            - text: 🐕 Datadog
              url: "https://app.datadoghq.eu/logs?query=cluster:${{ steps.set-context.outputs.CLUSTER }}%20namespace:${{ inputs.SERVICE_NAMESPACE }}&cols=privatedns,servicename"

    outputs:
      SHA_SHORT: ${{ steps.git-sha.outputs.SHA_SHORT }}
      IMAGE_SHA: ${{ steps.git-sha.outputs.IMAGE_SHA }}
      IMAGE_EXISTS: ${{ steps.check-image-ecr.outputs.IMAGE_EXISTS }}
      CLUSTER: ${{ steps.set-context.outputs.CLUSTER }}
      JIRA_CODE: ${{ steps.set-context.outputs.JIRA_CODE }}
      IMAGE_TAG: ${{ steps.set-context.outputs.IMAGE_TAG }}
      CREATE_TAG_LATEST: ${{ steps.set-context.outputs.CREATE_TAG_LATEST }}
