name: terraform deploy common workflow

on:
  workflow_call:
    inputs:
      AWS_DEFAULT_REGION:
        required: true
        type: string
      CLUSTER:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID_TF:
        required: true
      AWS_SECRET_ACCESS_KEY_TF:
        required: true
      GH_TF_SSH_KEY:
        required: true

concurrency:
  group: deploy-common-${{ github.workflow }}-${{ inputs.CLUSTER }}
  cancel-in-progress: false

jobs:
  tf-common:
    name: Tf common on cluster '${{ inputs.CLUSTER }}'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check required inputs
        run: |
          if [ -z "${{ inputs.AWS_DEFAULT_REGION }}" ]; then
            echo "::error title=Deploy common::Input AWS_DEFAULT_REGION is empty"
            exit 1
          fi
          if [ -z "${{ inputs.CLUSTER }}" ]; then
            echo "::error title=Deploy common::Input CLUSTER is empty"
            exit 1
          fi

      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TF }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TF }}
          aws-region: ${{ inputs.AWS_DEFAULT_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: v1.3.6

      # Common part
      - name: Terraform config global (init / validate / apply)
        env:
          GIT_SSH_COMMAND: "echo '${{ secrets.GH_TF_SSH_KEY }}' > id_rsa
            && ssh-keyscan github.com > known_hosts
            && chmod 600 id_rsa known_hosts
            && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
        working-directory: ./.terraform
        run: |
          if [ -d ./common/config-global ]; then
            cd ./common/config-global
            terraform version | head -1
            terraform init -upgrade
            terraform validate -no-color
            terraform apply -auto-approve
          else
            echo "::warning title=Deploy common::Terraform dir './common/config-global' does not exists (but it might be on purpose)"
          fi

      - name: Terraform config cluster '${{ inputs.CLUSTER }}' (init / validate / apply)
        env:
          GIT_SSH_COMMAND: "echo '${{ secrets.GH_TF_SSH_KEY }}' > id_rsa
            && ssh-keyscan github.com > known_hosts
            && chmod 600 id_rsa known_hosts
            && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
        working-directory: ./.terraform
        run: |
          if [ -d ./common/config-cluster ]; then
            cd ./common/config-cluster
            terraform init -reconfigure -upgrade -backend-config=backend-${{ inputs.CLUSTER }}.conf
            terraform validate -no-color
            terraform apply -auto-approve -var-file terraform-${{ inputs.CLUSTER }}.tfvars
          else
            echo "::warning title=Deploy common::Terraform dir './common/config-cluster' does not exists (but it might be on purpose)"
          fi
