name: 👉 Force cancelation of running workflow
run-name: ${{ github.ref_name }} to ${{ inputs.TARGET_WORKFLOW }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      TARGET_WORKFLOW:
        description: 'Select the running workflow to cancel'
        required: true
        type: choice
        options: ${{fromJson(steps.list_runs.outputs.running_workflows)}}

jobs:
  cancel-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Workflow
        run: |
          response=$(gh api \
            --method POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository_owner }}/${{ github.repository_name }}/actions/runs/${{ github.event.inputs.TARGET_WORKFLOW }}/force-cancel)
          echo "Cancellation response: $response"
    env:
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}