name: List Running Workflows

on:
    workflow_run:
      workflows: ['*']
      types:
        - requested
    

jobs:
  list-running-workflows:
    runs-on: ubuntu-latest
    outputs:
      running-workflows: ${{ steps.get_runs.outputs.running_workflows }}
    steps:
      - name: Get running workflows
        id: get_runs
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          ORG="${{ github.event.organization }}"
          REPO="${{ github.repository }}"
          API_URL="https://api.github.com/$ORG/$REPO/actions/runs"

          response=$(curl -sSL -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" "$API_URL")

          echo "::set-output name=running_workflows::$(echo "$response" | jq -c '[.workflow_runs[] | select(.status == "in_progress") | {name: .name, id: .id}]')"