name: Main workflow

on:
  workflow_call:
    inputs:
      AWS_DEFAULT_REGION:
        required: false
        type: string
        default: eu-west-3
      CLUSTER:
        required: true
        type: string
      SERVICE_NAMESPACE:
        required: true
        type: string
      SERVICES:
        description: "Services list for matrix strategy"
        required: true
        type: string
      IMAGE_NAMES:
        description: "Images list for matrix strategy"
        required: true
        type: string
      IMAGE_SHA:
        required: true
        type: string
      IMAGE_TAG:
        required: true
        type: string
      IMAGE_EXISTS:   # booleans must be treated as string
        required: true
        type: string
      CREATE_TAG_LATEST:
        required: true
        type: string
      SHA_SHORT:
        description: "Git commit SHA short (without 'sha-' prefix)"
        required: false
        type: string
        default: ''
      JIRA_CODE:
        required: false
        type: string
        default: ''
      DOCKERFILE_BUILD_CONTEXT:
        required: false
        type: string
        default: '.'
      FORCE_DEPLOYMENT:
        required: false
        type: string
        default: 'false'
      NOTIFICATIONS_JIRA:
        required: false
        type: string
        default: 'true'
      NOTIFICATIONS_TEAMS:
        required: false
        type: string
        default: 'true'
    secrets:
      AWS_ACCESS_KEY_ID_TF:
        required: true
      AWS_SECRET_ACCESS_KEY_TF:
        required: true
      GH_TF_SSH_KEY:
        required: true
      MS_TEAMS_WEBHOOK_URI:
        required: true
      JIRA_USER_EMAIL:
        required: true
      JIRA_API_TOKEN:
        required: true

concurrency:
  group: main-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Env context is not available in reusable workflows (with, if, run)
# See https://github.com/actions/runner/issues/480
# env: ...

jobs:
  # check-context:
  #   uses: Sonergia/github-reusable-workflows/.github/workflows/check-context.yml@2.x
  #   with:
  #     AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}
  #     CLUSTER: ${{ inputs.CLUSTER }}
  #     SERVICE_NAMESPACE: ${{ inputs.SERVICE_NAMESPACE }}
  #     SERVICES: ${{ inputs.SERVICES }}
  #     IMAGE_NAMES: ${{ inputs.IMAGE_NAMES }}
  #     SHA_SHORT: ${{ inputs.SHA_SHORT }}
  #     NOTIFICATIONS_TEAMS: ${{ inputs.NOTIFICATIONS_TEAMS }}
  #   secrets:
  #     AWS_ACCESS_KEY_ID_TF: ${{ secrets.AWS_ACCESS_KEY_ID_TF }}
  #     AWS_SECRET_ACCESS_KEY_TF: ${{ secrets.AWS_SECRET_ACCESS_KEY_TF }}
  #     MS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}

  # # Application software dedicated build process
  # build-application:
  #   needs:
  #     - check-context
  #   # The "uses" statement that calls the reusable workflow can’t evaluate expressions yet. That means the repo name, branch, etc. must be hardcoded.
  #   uses: ${{ inputs.APPLICATION_BUILD_FILE_PATH }}
  #   if: ${{ inputs.APPLICATION_BUILD_FILE_PATH != '' && inputs.IMAGE_EXISTS == 'false' }}

#--------------------------------------------------------

  # Terraform deploy common (with reusable workflows)
  deploy-common:
    uses: Sonergia/github-reusable-workflows/.github/workflows/deploy-common.yml@2.x
    with:
      AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}
      CLUSTER: ${{ inputs.CLUSTER }}
    secrets:
      AWS_ACCESS_KEY_ID_TF: ${{ secrets.AWS_ACCESS_KEY_ID_TF }}
      AWS_SECRET_ACCESS_KEY_TF: ${{ secrets.AWS_SECRET_ACCESS_KEY_TF }}
      GH_TF_SSH_KEY: ${{ secrets.GH_TF_SSH_KEY }}

  # Build and push docker image (with reusable workflows)
  build-docker:
    needs:
      - deploy-common
    uses: Sonergia/github-reusable-workflows/.github/workflows/build-docker.yml@2.x
    if: ${{ inputs.IMAGE_EXISTS == 'false' }}
    with:
      AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}
      SERVICE_NAMESPACE: ${{ inputs.SERVICE_NAMESPACE }}
      IMAGE_NAMES: ${{ inputs.IMAGE_NAMES }}
      IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
      CREATE_TAG_LATEST: ${{ inputs.CREATE_TAG_LATEST }}
      DOCKERFILE_BUILD_CONTEXT: ${{ inputs.DOCKERFILE_BUILD_CONTEXT }}
    secrets:
      AWS_ACCESS_KEY_ID_TF: ${{ secrets.AWS_ACCESS_KEY_ID_TF }}
      AWS_SECRET_ACCESS_KEY_TF: ${{ secrets.AWS_SECRET_ACCESS_KEY_TF }}

  # Terraform deploy service (with reusable workflows)
  deploy-service:
    needs:
      - build-docker
      - deploy-common
    uses: Sonergia/github-reusable-workflows/.github/workflows/deploy-service.yml@2.x
    # always() condition avoid this jobs to be skipped if needed jobs are skipped
    if: always()
    with:
      AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}
      CLUSTER: ${{ inputs.CLUSTER }}
      SERVICE_NAMESPACE: ${{ inputs.SERVICE_NAMESPACE }}
      SERVICES: ${{ inputs.SERVICES }}
      IMAGE_SHA: ${{ inputs.IMAGE_SHA }}
      IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
      IMAGE_EXISTS: ${{ inputs.IMAGE_EXISTS }}
      BUILD_DOCKER_RESULT: ${{ needs.build-docker.result }}
      FORCE_DEPLOYMENT: ${{ inputs.FORCE_DEPLOYMENT }}
      JIRA_CODE: ${{ inputs.JIRA_CODE }}
      NOTIFICATIONS_JIRA: ${{ inputs.NOTIFICATIONS_JIRA }}
      NOTIFICATIONS_TEAMS: ${{ inputs.NOTIFICATIONS_TEAMS }}
    secrets:
      AWS_ACCESS_KEY_ID_TF: ${{ secrets.AWS_ACCESS_KEY_ID_TF }}
      AWS_SECRET_ACCESS_KEY_TF: ${{ secrets.AWS_SECRET_ACCESS_KEY_TF }}
      GH_TF_SSH_KEY: ${{ secrets.GH_TF_SSH_KEY }}
      MS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
