name: ♻️ Merge tag or branch into another branch (main, master or delivery)

on:
  workflow_call:
    inputs:
      TARGET_BRANCH:
        required: false
        type: string
        default: master
    secrets:
      access-token:
        description: "A token passed from the caller workflow"
        required: true

jobs:
  merge:
    name: Merge '${{ github.ref }}' into ${{ inputs.TARGET_BRANCH }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "match=true" >> $GITHUB_OUTPUT
          else
            echo "::error title=Check tag::${{ github.ref }} n'est pas un tag de livraison (format sémantique: 1.2.3)"
            exit 1
          fi
      
      - name: Check branch
        id: check-branch
        run: |
          if [[ ! ${{ inputs.TARGET_BRANCH }} =~ ^(main|master|delivery)$ ]]; then
            echo "::error title=Check branch::Seules les branches main, master et delivery sont supportées"
            exit 1
          fi

      - name: Merge into ${{ inputs.TARGET_BRANCH }}
        if: steps.check-tag.outputs.match == 'true'
        uses: julbme/gh-action-merge-branch@v1
        with:
          from: ${{ github.ref }}
          to: ${{ inputs.TARGET_BRANCH }}
          message: Merge ${{ github.ref }} into ${{ inputs.TARGET_BRANCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.access-token }}
